spring.application.name=jelajahbandung
server.forward-headers-strategy=framework
# server.use-forward-headers=true # Optional but framework should be enough
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# Let the browser find it naturally from the context
# Remove relative paths if they are causing 500s due to mismatched prefixes

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jelajahbandungdev
spring.datasource.username=postgres
spring.datasource.password=p4ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload
file.upload-dir=uploads

# Email Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=ec8b3588e4ba16
spring.mail.password=your-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Fontee Configuration
fontee.token=your-fontee-token
